/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppDiscoverRouteImport } from './routes/app.discover'
import { Route as AppFriendsRouteImport } from './routes/app.friends'
import { Route as AppInboxRouteImport } from './routes/app.inbox'
import { Route as AppSavedRouteImport } from './routes/app.saved'
import { Route as AppSearchRouteImport } from './routes/app.search'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppWelcomeRouteImport } from './routes/app.welcome'
import { Route as AppDmPersonIdRouteImport } from './routes/app.dm.$personId'
import { Route as AppInviteCommunityIdRouteImport } from './routes/app.invite.$communityId'
import { Route as AppCommunityCommunityIdChannelIdRouteImport } from './routes/app.community.$communityId.$channelId'
import { Route as AppCommunityCommunityIdSettingsRouteImport } from './routes/app.community.$communityId.settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppDiscoverRoute = AppDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AppRoute,
} as any)
const AppFriendsRoute = AppFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppSavedRoute = AppSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppWelcomeRoute = AppWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AppRoute,
} as any)
const AppDmPersonIdRoute = AppDmPersonIdRouteImport.update({
  id: '/dm/$personId',
  path: '/dm/$personId',
  getParentRoute: () => AppRoute,
} as any)
const AppInviteCommunityIdRoute = AppInviteCommunityIdRouteImport.update({
  id: '/invite/$communityId',
  path: '/invite/$communityId',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunityCommunityIdChannelIdRoute =
  AppCommunityCommunityIdChannelIdRouteImport.update({
    id: '/community/$communityId/$channelId',
    path: '/community/$communityId/$channelId',
    getParentRoute: () => AppRoute,
  } as any)
const AppCommunityCommunityIdSettingsRoute =
  AppCommunityCommunityIdSettingsRouteImport.update({
    id: '/community/$communityId/settings',
    path: '/community/$communityId/settings',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/app/discover': typeof AppDiscoverRoute
  '/app/friends': typeof AppFriendsRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/saved': typeof AppSavedRoute
  '/app/search': typeof AppSearchRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/welcome': typeof AppWelcomeRoute
  '/app/': typeof AppIndexRoute
  '/app/dm/$personId': typeof AppDmPersonIdRoute
  '/app/invite/$communityId': typeof AppInviteCommunityIdRoute
  '/app/community/$communityId/$channelId': typeof AppCommunityCommunityIdChannelIdRoute
  '/app/community/$communityId/settings': typeof AppCommunityCommunityIdSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/app/discover': typeof AppDiscoverRoute
  '/app/friends': typeof AppFriendsRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/saved': typeof AppSavedRoute
  '/app/search': typeof AppSearchRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/welcome': typeof AppWelcomeRoute
  '/app': typeof AppIndexRoute
  '/app/dm/$personId': typeof AppDmPersonIdRoute
  '/app/invite/$communityId': typeof AppInviteCommunityIdRoute
  '/app/community/$communityId/$channelId': typeof AppCommunityCommunityIdChannelIdRoute
  '/app/community/$communityId/settings': typeof AppCommunityCommunityIdSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/app/discover': typeof AppDiscoverRoute
  '/app/friends': typeof AppFriendsRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/saved': typeof AppSavedRoute
  '/app/search': typeof AppSearchRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/welcome': typeof AppWelcomeRoute
  '/app/': typeof AppIndexRoute
  '/app/dm/$personId': typeof AppDmPersonIdRoute
  '/app/invite/$communityId': typeof AppInviteCommunityIdRoute
  '/app/community/$communityId/$channelId': typeof AppCommunityCommunityIdChannelIdRoute
  '/app/community/$communityId/settings': typeof AppCommunityCommunityIdSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/app/discover'
    | '/app/friends'
    | '/app/inbox'
    | '/app/saved'
    | '/app/search'
    | '/app/settings'
    | '/app/welcome'
    | '/app/'
    | '/app/dm/$personId'
    | '/app/invite/$communityId'
    | '/app/community/$communityId/$channelId'
    | '/app/community/$communityId/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/app/discover'
    | '/app/friends'
    | '/app/inbox'
    | '/app/saved'
    | '/app/search'
    | '/app/settings'
    | '/app/welcome'
    | '/app'
    | '/app/dm/$personId'
    | '/app/invite/$communityId'
    | '/app/community/$communityId/$channelId'
    | '/app/community/$communityId/settings'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/app/discover'
    | '/app/friends'
    | '/app/inbox'
    | '/app/saved'
    | '/app/search'
    | '/app/settings'
    | '/app/welcome'
    | '/app/'
    | '/app/dm/$personId'
    | '/app/invite/$communityId'
    | '/app/community/$communityId/$channelId'
    | '/app/community/$communityId/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/discover': {
      id: '/app/discover'
      path: '/discover'
      fullPath: '/app/discover'
      preLoaderRoute: typeof AppDiscoverRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/friends': {
      id: '/app/friends'
      path: '/friends'
      fullPath: '/app/friends'
      preLoaderRoute: typeof AppFriendsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inbox': {
      id: '/app/inbox'
      path: '/inbox'
      fullPath: '/app/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/saved': {
      id: '/app/saved'
      path: '/saved'
      fullPath: '/app/saved'
      preLoaderRoute: typeof AppSavedRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/search': {
      id: '/app/search'
      path: '/search'
      fullPath: '/app/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/welcome': {
      id: '/app/welcome'
      path: '/welcome'
      fullPath: '/app/welcome'
      preLoaderRoute: typeof AppWelcomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dm/$personId': {
      id: '/app/dm/$personId'
      path: '/dm/$personId'
      fullPath: '/app/dm/$personId'
      preLoaderRoute: typeof AppDmPersonIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/invite/$communityId': {
      id: '/app/invite/$communityId'
      path: '/invite/$communityId'
      fullPath: '/app/invite/$communityId'
      preLoaderRoute: typeof AppInviteCommunityIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/community/$communityId/$channelId': {
      id: '/app/community/$communityId/$channelId'
      path: '/community/$communityId/$channelId'
      fullPath: '/app/community/$communityId/$channelId'
      preLoaderRoute: typeof AppCommunityCommunityIdChannelIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/community/$communityId/settings': {
      id: '/app/community/$communityId/settings'
      path: '/community/$communityId/settings'
      fullPath: '/app/community/$communityId/settings'
      preLoaderRoute: typeof AppCommunityCommunityIdSettingsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDiscoverRoute: typeof AppDiscoverRoute
  AppFriendsRoute: typeof AppFriendsRoute
  AppInboxRoute: typeof AppInboxRoute
  AppSavedRoute: typeof AppSavedRoute
  AppSearchRoute: typeof AppSearchRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppWelcomeRoute: typeof AppWelcomeRoute
  AppIndexRoute: typeof AppIndexRoute
  AppDmPersonIdRoute: typeof AppDmPersonIdRoute
  AppInviteCommunityIdRoute: typeof AppInviteCommunityIdRoute
  AppCommunityCommunityIdChannelIdRoute: typeof AppCommunityCommunityIdChannelIdRoute
  AppCommunityCommunityIdSettingsRoute: typeof AppCommunityCommunityIdSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDiscoverRoute: AppDiscoverRoute,
  AppFriendsRoute: AppFriendsRoute,
  AppInboxRoute: AppInboxRoute,
  AppSavedRoute: AppSavedRoute,
  AppSearchRoute: AppSearchRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppWelcomeRoute: AppWelcomeRoute,
  AppIndexRoute: AppIndexRoute,
  AppDmPersonIdRoute: AppDmPersonIdRoute,
  AppInviteCommunityIdRoute: AppInviteCommunityIdRoute,
  AppCommunityCommunityIdChannelIdRoute: AppCommunityCommunityIdChannelIdRoute,
  AppCommunityCommunityIdSettingsRoute: AppCommunityCommunityIdSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
